.github/workflows/main.yml
DBS/README.md

Die TOC action erstellt automatisch ein Inhaltsverzeichnis in jeder `.md` Datei und committed sie.
Ist sicher praktisch. 😄
Und dann hab ich noch ein paar kleinere Dingen gemacht, viel stand aber schon drin, von daher...

TOC-Action and minor modifications

---

.github/workflows/main.yml
DBS/README.md

@ZeroPointMax @RvNovae Seid ihr mit dem quick and easy fix einverstanden?
EDIT: Ich hatte eigentlich die Hoffnung, dass der neue Commit der alten PR hinzugefügt wird, aber ich hätte das wahrscheinlich besser auf einer eigenen Branch machen sollen 😅

TOCGEN für alle branches außer main

---

DBS/README.md
DBS/resources/erm-bsp.svg

To illustrate database schemas, i made a simple SVG in Inkscape.

DBS PIA 06.10.2020: added ERM/schema sample from today's lecture

---

.github/workflows/main.yml

Wie besprochen würde ich einfach die automatischen PRs für die TOC-Action aktivieren und hoffen, dass das unser Problem löst.

TOC: enable PRs

---

.github/workflows/main.yml

Proposed changes by @RvNovae

---

.github/workflows/main.yml

Trigger TOC-Workflow on pull_request

---

DBS/README.md
README.md

Binäre Baume habe ich erstmal übersprungen, weil wir das eigentlich alles in ALGO schon hatten mit dem Unterscheid, dass Dodo eine andere Schreibweise benutzt 😅

DBS: Objektorientiertes Datenmodell & Sprachschnittstellen

---

DBS/README.md
SWE/README.md

Ist sicher nicht 100% vollständig. Sind größtenteils die Dinge, die er angeschrieben hat.

SWE Mitschriften 09.10.2020

---

PRO/README.md

und zusätzlich: RES vergessener commit

RES vom 14.10.2020: Windows Netzlaufwerke, Ping, Firewall

---

RES/README.md

I accidentally  deleted some notes with closing #17 and merging with #18. 
Oof, Thx Github for saving my ***

RES Max: Recovery PR

---

RES/README.md

Im Grunde netsh Firewall Verwaltung...

netsh firewall ping rules

---

RES/README.md

mögliche Prüfungsfragen hinzugefügt, haben zwar kaum einen Schwierigkeitsgrad, aber lieber zu viel als zu wenig :D

Mögliche Prüfungsfragen für Betriebssystemverwaltung

---

PRO/README.md

PRO: Restore 9adc527f3072d0b661

---

PRO/README.md

Wiederholungen wurden entfernt und die Formatierung teilweise etwas abgeändert

PRO: Cleanup

---

RES/vortrag/2020-11/ssh_max_basti/README.md

Wir haben mit HackMD Notizen zum SSH-Vortrag Nov. 2020 erstellt.
Die müssten aus dem Fork irgendwie mal im "echten" Repo landen

RES: Vortrag SSH Notizen aus HackMD

---

PRO/README.md
RES/README.md

RES: Weitere Prüfungsfragen

---

RES/README.md

Wir sind mit Herr Günther zur Übung einige Klausurfragen durchgegangen. Diese wurden direkt sinngemäß übernommen

Weitere Prüfungsfragen

---

.github/workflows/toc.yml
README.md

Die README vom Repository ist seit dem Anfang des Semesters unverändert. Im vergangenen Semester mit vielen "Nicht-Live"-Veranstaltungen konnte ich mich mit der Checkliste gut organisieren, aber dieses Semester passt das mit den vielen Live-Veranstaltungen meiner Meinung nach nicht.  Daher hier mein Vorschlag für eine neue README.

Ansprechendere README

---

.github/workflows/pandoc.yml
DBS/README.md
DBS/praktikum/README.md
NET/README.md
PRO/README.md
RES/README.md
SWE/README.md

Ich weiß nicht warum, aber es funktioniert in allen Dokumenten außer `RES`. Der LaTeX output ist aber aus meiner Sicht korrekt/unterscheidet sich von den funktionierenden Dokumenten nicht 🤔
Should resolve #71 
Die ganzen Commits bitte wieder ignorieren. Die Actions lassen sich wirklich blöd testen 😅

fix pagebreaks, implement newpage and clearpage (fixes #71)

---

.github/workflows/pandoc.yml
DBS/README.md
NET/README.md
PRO/README.md
RES/README.md
SWE/README.md

Im Gegensatz zur vorgeschlagenen Syntax im Issue habe ich mich für Folgende entschieden, um Probleme zu vermeiden, wenn man versehentlich mal ein `-` mehr an einen Kommentar hängt.
```md
```
Titel und Semester werden wie folgt in der Kopfzeile auf jeder Seite dargestellt:
Wenn wir wöllten, könnten wir Rechts/Mittig/Links in Kopf und Fußzeile beliebige Texte einfügen, für Vorschläge bin ich da gerne noch offen.
Des Weiteren habe ich erweitertes Syntax-Highlighting für Code-Blöcke aktiviert:
Die PDFs könnt ihr euch in [meiner Fork](https://github.com/Steve2955/dhge-pi19-sem3/releases/tag/pdf-release) ansehen.
resolves #76

frontmatter support

---

NET/README.md

Nehme mal an, dass das einfach ein typos sind

Fix: typos

---

NET/README.md

fix wrong Hyperlink Syntax

---

NET/README.md

Fragt nicht was das Problem war, ich habe ewig versucht zwischen verschiedenen Character-Encodings umzuwandeln und irgendwann kam dann nur noch der Fehler `too deeply nested`, den habe ich dann auch noch behoben.
resolves #113

fix pandoc issue(s)

---

SWE-KASCHE/README.md

remove mvp from pretotype list

---

SWE-KASCHE/README.md

Altough barely noticable, a table is broken rn (missing newline).
Relevant for #126

attempt to fix broken table
